-- DDL subset for LUCCA Inicio/Login/Usuarios
-- Generated: 2026-03-09T23:46:42.718061+00:00

CREATE TABLE [dbo].[Usuarios](
	[CODIGO] [int] NOT NULL,
	[LOGIN] [char](10) NULL,
	[PASSWORD] [char](10) NULL,
	[NOMBRE] [varchar](100) NULL,
	[NOEMPLEADO] [int] NULL,
	[PUESTO] [char](30) NULL,
	[AREA] [int] NULL,
	[CUADRILLA] [char](4) NULL,
	[DERECHOALMACEN1] [tinyint] NULL,
	[DERECHOALMACEN2] [tinyint] NULL,
	[DERECHOALMACEN3] [tinyint] NULL,
	[DERECHOALMACEN4] [tinyint] NULL,
	[DERECHOS1] [tinyint] NULL,
	[DERECHOS2] [tinyint] NULL,
	[DERECHOS3] [tinyint] NULL,
	[DERECHOS4] [tinyint] NULL,
	[DERECHO5] [tinyint] NULL,
	[DERECHO6] [tinyint] NULL,
	[DERECHO7] [tinyint] NULL,
	[DERECHO8] [tinyint] NULL,
	[DERECHO9] [tinyint] NULL,
	[DERECHO10] [tinyint] NULL,
	[DERECHO11] [tinyint] NULL,
	[DERECHO12] [tinyint] NULL,
	[DERECHO13] [tinyint] NULL,
	[NOMINA] [tinyint] NULL,
	[CUENTADEUDORDIVERSO] [int] NULL,
	[CTADEUDORDIVINTERNACIONAL] [int] NULL,
	[CTADEUDORDIVOTROSGASTOS] [int] NULL,
	[RELEVANTECALIDAD] [decimal](1, 0) NULL,
	[HORARIO] [decimal](3, 0) NULL,
	[ULTIMOREGISTRO] [int] NULL,
	[BLOQUEADO] [tinyint] NULL,
	[FIRMA] [varchar](100) NULL,
	[AUTBIEN] [smallint] NULL,
	[AUTSERV] [smallint] NULL,
	[AUTVIAT] [smallint] NULL,
	[AUTTODASAREAS] [tinyint] NULL,
	[OPERADORALMACEN] [smallint] NULL,
	[SUPERVISORALMACEN] [tinyint] NULL,
	[ADMINISTRADORALMACENES] [tinyint] NULL,
	[ALMACENFAVORITO] [smallint] NULL,
	[ReceptorOficios] [int] NULL,
	[FOTO] [text] NULL,
	[RowVer] [timestamp] NOT NULL,
 CONSTRAINT [PK__Usuarios__CC87E12718C3FA05] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[Areax](
	[CODIGO] [int] NOT NULL,
	[DESCRIPCION] [varchar](200) NULL,
	[SEGMENTO1] [decimal](3, 0) NOT NULL,
	[SEGMENTO2] [decimal](3, 0) NULL,
	[SEGMENTO3] [decimal](3, 0) NULL,
	[SEGMENTO4] [decimal](5, 0) NULL,
	[RESPONSABLEAREA] [char](35) NULL,
	[PUESTO] [char](20) NULL,
	[GERENTEDELAREA] [char](40) NULL,
	[CENTRODECOSTO] [varchar](10) NULL,
	[NIVEL] [smallint] NULL,
	[Activo] [tinyint] NULL,
 CONSTRAINT [PK__Areas_2019] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[DatosGrales](
	[CODIGO] [smallint] NOT NULL,
	[PERMITIRCAPTURAPROYECTOADQUISICIONES] [tinyint] NULL,
	[LETRASENCONTREASENA] [tinyint] NULL,
	[NUMEROSENCONTRASENA] [tinyint] NULL,
	[NODIASINHABLITARINACTIVO] [tinyint] NULL,
	[FIRMAREQUISICIONES] [varchar](39) NULL,
	[FIRMAORDENESCOMPRA] [varchar](39) NULL,
	[AUTORIZACHEQUES] [varchar](39) NULL,
	[NOMBREENTIDAD] [varchar](100) NULL,
	[CLAVE] [varchar](10) NULL,
	[TIEMPOINACTIVIDADBLOQUEO] [smallint] NULL,
	[CALLE] [varchar](40) NULL,
	[NO] [varchar](10) NULL,
	[COL] [varchar](20) NULL,
	[CIUDAD] [varchar](25) NULL,
	[MUNICIPIO] [varchar](60) NULL,
	[ESTADO] [varchar](20) NULL,
	[CP] [varchar](5) NULL,
	[TEL] [varchar](10) NULL,
	[TEL2] [varchar](10) NULL,
	[FORMATORECIBO] [int] NULL,
	[CTARECSPROPIOS] [int] NULL,
	[INTERESMENSUAL] [decimal](5, 2) NULL,
	[CTANOMINA] [int] NULL,
	[DIRAYUDA] [varchar](64) NULL,
	[PERMITIRSOBREGIRO] [tinyint] NULL,
	[FACTORPREDIAL] [decimal](7, 2) NULL,
	[REALIZA] [varchar](50) NULL,
	[REVISA] [varchar](50) NULL,
	[AUTORIZA] [varchar](50) NULL,
	[PTOPRECOMP] [tinyint] NULL,
	[USARPOLORDEN] [tinyint] NULL,
	[LIMITERETENCION] [decimal](13, 2) NULL,
	[REGGAS35] [tinyint] NULL,
	[NOSALRIOS] [smallint] NULL,
	[CTAGAS] [varchar](100) NULL,
	[IMPSMDF] [decimal](15, 2) NULL,
	[CODBOLAVION] [int] NULL,
	[CODTUA] [int] NULL,
	[CODAUTOBUS] [int] NULL,
	[CTADEVOLUCIONING] [int] NULL,
	[USARCTACONTRIBUYENTE] [tinyint] NULL,
	[OBLIGADORETENERIVA] [tinyint] NULL,
	[CTAUTILIDADPERDIDACAMBIARIA] [int] NULL,
	[CTAPERDIDACAMBIARIA] [int] NULL,
	[REGIMENFISCAL] [varchar](35) NULL,
	[FACTORRIESGO] [int] NULL,
	[REGISTROPATRONAL] [varchar](20) NULL,
	[RFC] [varchar](13) NULL,
	[CODFERRY] [int] NULL,
	[NOMBREAUTRESG] [varchar](50) NULL,
	[PUESTOAUTRESG] [varchar](50) NULL,
	[TITULODOCTO] [varchar](50) NULL,
	[NOMSISTEM] [varchar](50) NULL,
	[SECTOR] [varchar](10) NULL,
	[UNIDADRESPONSABLE] [varchar](10) NULL,
	[UNIDADPRESUPUESTAL] [varchar](10) NULL,
	[ESTADOPRES] [varchar](10) NULL,
	[GASTOESPECIFICO] [varchar](10) NULL,
	[MUNICIPIODEF] [varchar](10) NULL,
	[GENERO] [tinyint] NULL,
	[PORCRETIVA] [decimal](6, 4) NULL,
	[PORCRETISR] [decimal](6, 4) NULL,
	[CTARETIVA] [int] NULL,
	[CTARETISR] [int] NULL,
	[PRIVILEGIOLOCAL] [tinyint] NULL,
	[PORCPRIVILEGIO] [smallint] NULL,
	[PRIVILEGIOPYME] [tinyint] NULL,
	[PORCIVAXPAGAR] [decimal](7, 2) NULL,
	[CUENTAIVAXPAGAR] [int] NULL,
	[LIMITECOMPRACAJACHICA] [decimal](15, 2) NULL,
	[LIMITEFONDOREV] [decimal](15, 2) NULL,
	[NIVELESGLOSA] [smallint] NULL,
	[SEPARAROCACTIVOS] [tinyint] NULL,
	[NOMAUTPRESUPUETOOC] [varchar](50) NULL,
	[SALDOACUMULADO] [tinyint] NULL,
	[CTABANPUENTE] [int] NULL,
	[CABECERASECTOR] [varchar](60) NULL,
	[CAMBIOFECHA] [tinyint] NULL,
	[APAGAAPLICA] [tinyint] NULL,
	[DIOTEGRESO] [tinyint] NULL,
	[PregUbica] [tinyint] NULL,
	[Sistema] [tinyint] NULL,
	[IMAGENLOGO] [image] NULL,
	[PuestoAutOC] [varchar](50) NULL,
	[PuestoAutOCPres] [varchar](50) NULL,
	[AutFalloLicita] [varchar](50) NULL,
	[PuestoAutFLicita] [varchar](50) NULL,
	[Poder] [tinyint] NULL,
	[PorcResico] [decimal](15, 2) NULL,
	[CtaContResico] [int] NULL,
	[AutComiAlfa] [varchar](50) NULL,
	[PuestComiAlfa] [varchar](50) NULL,
	[CodUsuSustituyeAut] [int] NULL,
	[AutComiBeta] [varchar](50) NULL,
	[PuestComiBeta] [varchar](50) NULL,
	[ViaticosFE] [int] NULL,
	[SolSistema] [tinyint] NULL,
	[TipoDeNomina] [varchar](50) NULL,
 CONSTRAINT [PK__DatosGra__CC87E12715261146] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [dbo].[ConfInter](
	[CODIGO] [tinyint] NOT NULL,
	[APLICARTIPOGASTO] [tinyint] NULL,
	[SEGMENTO] [tinyint] NULL,
	[DIGITOINICIAL] [tinyint] NULL,
	[NODIGITOS] [tinyint] NULL,
	[APLICARPRESUPUESTAL] [tinyint] NULL,
	[SEGMENTOPRES] [tinyint] NULL,
	[DIGITOINICIALPRES] [tinyint] NULL,
	[NODIGITOSPRES] [tinyint] NULL,
	[APLICARPRESORDEN] [tinyint] NULL,
	[SEGMENTOPORD] [tinyint] NULL,
	[DIGITOINICIALPORD] [tinyint] NULL,
	[NODIGITOSPORD] [tinyint] NULL,
	[APLICARORIGENRECS] [tinyint] NULL,
	[SEGMENTOORI] [tinyint] NULL,
	[DIGITOINICIALORI] [tinyint] NULL,
	[NODIGITOSORI] [tinyint] NULL,
	[APLICARCENTROCOSTO] [tinyint] NULL,
	[SEGMENTOCC] [tinyint] NULL,
	[DIGITOINICIALCC] [tinyint] NULL,
	[NODIGITOSCC] [tinyint] NULL,
	[APLICARFFS] [tinyint] NULL,
	[SEGMENTOFFS] [tinyint] NULL,
	[DIGITOINICIALFFS] [tinyint] NULL,
	[NODIGITOSFFS] [tinyint] NULL,
	[APLICARFUN] [tinyint] NULL,
	[SEGMENTOFUN] [tinyint] NULL,
	[DIGITOINICIALFUN] [tinyint] NULL,
	[NODIGITOSFUN] [tinyint] NULL,
	[APLICARSFN] [tinyint] NULL,
	[SEGMENTOSFN] [tinyint] NULL,
	[DIGITOINICIALSFN] [tinyint] NULL,
	[NODIGITOSSFN] [tinyint] NULL,
	[APLICARPROGRAMA] [tinyint] NULL,
	[SEGMENTOPROG] [tinyint] NULL,
	[DIGITOINICIALPROG] [tinyint] NULL,
	[NODIGITOSPROG] [tinyint] NULL,
	[APLICARPROYECTO] [tinyint] NULL,
	[SEGMENTOPROY] [tinyint] NULL,
	[DIGITOINICIALPROY] [tinyint] NULL,
	[NODIGITOSPROY] [tinyint] NULL,
	[APLICARIDCONT] [tinyint] NULL,
	[SEGMENTOIDCONT] [tinyint] NULL,
	[DIGITOINICIALIDCONT] [tinyint] NULL,
	[NODIGITOSIDCONT] [tinyint] NULL,
	[APLICARCASO1] [tinyint] NULL,
	[VALOR1] [smallint] NULL,
	[SEGMENTOCASO1] [tinyint] NULL,
	[DIGITOINICIALCASO1] [tinyint] NULL,
	[NODIGITOSCASO1] [tinyint] NULL,
	[USO1] [varchar](15) NULL,
	[APLICARCASO2] [tinyint] NULL,
	[VALOR2] [smallint] NULL,
	[SEGMENTOCASO2] [tinyint] NULL,
	[DIGITOINICIALCASO2] [tinyint] NULL,
	[NODIGITOSCASO2] [tinyint] NULL,
	[USO2] [varchar](15) NULL,
	[APLICARCASO3] [tinyint] NULL,
	[VALOR3] [smallint] NULL,
	[SEGMENTOCASO3] [tinyint] NULL,
	[DIGITOINICIALCASO3] [tinyint] NULL,
	[NODIGITOSCASO3] [tinyint] NULL,
	[USO3] [varchar](15) NULL,
	[APLICARSUBGASTO] [tinyint] NULL,
	[SEGMENTOSUBGASTO] [tinyint] NULL,
	[DIGITOINICIALSUBGASTO] [tinyint] NULL,
	[NODIGITOSSUBGASTO] [tinyint] NULL,
	[APLICARAMPRED] [tinyint] NULL,
	[SEGMENTOAMPRED] [tinyint] NULL,
	[DIGITOINICIALAMPRED] [tinyint] NULL,
	[NODIGITOSAMPRED] [tinyint] NULL,
	[IDAMPLIACION] [smallint] NULL,
	[IDREDUCCION] [smallint] NULL,
	[APLICATIPOMOD] [tinyint] NULL,
	[SEMENTOTIPOMOD] [tinyint] NULL,
	[DIGITOINICIALTIPOMOD] [tinyint] NULL,
	[NODIGITOSTIPOMOD] [tinyint] NULL,
	[VALORINICIALTIPOMOD] [tinyint] NULL,
	[VALORFINALTIPOMOD] [tinyint] NULL,
	[APLICARAMO] [tinyint] NULL,
	[SEGMENTORAMO] [tinyint] NULL,
	[DIGITOINICIALRAMO] [tinyint] NULL,
	[NODIGITOSRAMO] [tinyint] NULL,
	[VALORRAMO] [smallint] NULL,
	[ALFARAMO] [tinyint] NULL,
	[APLICAIDPROG] [tinyint] NULL,
	[SEGMENTOIDPROG] [tinyint] NULL,
	[DIGITOINICIALIDPROG] [tinyint] NULL,
	[NODIGITOSIDPROG] [tinyint] NULL,
	[ALFAIDPROG] [tinyint] NULL,
	[ACTIVO] [smallint] NULL,
	[PASIVO] [smallint] NULL,
	[CAPITAL] [smallint] NULL,
	[INGRESOS] [smallint] NULL,
	[EGRESOS] [smallint] NULL,
	[PRESUPUESTO] [smallint] NULL,
	[APLICARGCC] [tinyint] NULL,
	[SEGMENTOGCC] [tinyint] NULL,
	[DIGITOINICIALGCC] [tinyint] NULL,
	[NODIGITOSGCC] [tinyint] NULL,
	[PORCIVA1] [tinyint] NULL,
	[CTAIVA1] [int] NULL,
	[PORCIVA2] [tinyint] NULL,
	[CTAIVA2] [int] NULL,
	[PORCIVA3] [tinyint] NULL,
	[CTAIVA3] [int] NULL,
	[SERVIDOR] [varchar](40) NULL,
	[BASEDATOS] [varchar](30) NULL,
	[USUARIO] [varchar](30) NULL,
	[CONTRASENA] [varchar](30) NULL,
	[APLICAIDPRESUPUESTAL] [tinyint] NULL,
	[SEGMENTOIDP] [tinyint] NULL,
	[DIGITOINICIALIDP] [tinyint] NULL,
	[NODIGITOSIDP] [tinyint] NULL,
	[AUTORIZADO] [smallint] NULL,
	[MODIFICADO] [smallint] NULL,
	[POREJERCER] [smallint] NULL,
	[PRECOMPROMETIDO] [smallint] NULL,
	[COMPROMETIDO] [smallint] NULL,
	[DEVENGADO] [smallint] NULL,
	[EJERCIDO] [smallint] NULL,
	[PAGADO] [smallint] NULL,
	[POREJECUTAR] [smallint] NULL,
	[DEVENGADA] [smallint] NULL,
	[RECAUDADA] [smallint] NULL,
	[REFERENCIAPROV] [varchar](10) NULL,
	[REFERENCIAEGRESO] [varchar](10) NULL,
	[REFERENCIAPRESPAG] [varchar](10) NULL,
	[REFERENCIAPRESEJE] [varchar](10) NULL,
	[REFERENCIAPRESDEV] [varchar](10) NULL,
	[REFERENCIAPRESPRECOMP] [varchar](10) NULL,
	[REFERENCIAPRESCOMP] [varchar](10) NULL,
	[REFERENCIAPRESPOREJECUTAR] [varchar](10) NULL,
	[REFERENCIAPRESDEVENGADA] [varchar](10) NULL,
	[REFERENCIAPRESRECAUDADA] [varchar](10) NULL,
	[CONCEPTOPROV] [varchar](15) NULL,
	[CONCEPTOEGRESO] [varchar](15) NULL,
	[CONCEPTOPRESPAG] [varchar](15) NULL,
	[CONCEPTOPRESEJER] [varchar](15) NULL,
	[CONCEPTOPRESDEV] [varchar](15) NULL,
	[CONCEPTOPRESPRECOMP] [varchar](15) NULL,
	[CONCEPTOPRESCOMP] [varchar](15) NULL,
	[CONCEPTOPRESPOREJECUTAR] [varchar](15) NULL,
	[CONCEPTOPRESDEVENGADA] [varchar](15) NULL,
	[CONCEPTOPRESRECAUDADA] [varchar](15) NULL,
	[ORIGENRECPROP] [varchar](12) NULL,
	[CTABANCOINGRESO] [int] NULL,
	[PRESUPUESTOENPOLORD] [tinyint] NULL,
	[UTILIZARCUENTASDEALMACEN] [tinyint] NULL,
	[SEGMENTOCOGALM] [tinyint] NULL,
	[DIGITOINICIALCOGALM] [tinyint] NULL,
	[NODIGITOSCOGALM] [tinyint] NULL,
	[CUENTAALMACEN] [varchar](100) NULL,
	[INCLUIRCOG] [tinyint] NULL,
	[UTLIZARXEXA] [tinyint] NULL,
	[SEGMENTOXEXA] [tinyint] NULL,
	[DIGITOINICIALXECA] [tinyint] NULL,
	[NODIGITOSXEXA] [tinyint] NULL,
	[IDXEXA] [smallint] NULL,
	[CTAXAPLICAR] [int] NULL,
	[SEGALMCOG] [tinyint] NULL,
	[APLICARDIGESPDIARIO] [tinyint] NULL,
	[SEGMENTOESPDIARIO] [tinyint] NULL,
	[INIESPDIARIO] [tinyint] NULL,
	[NODIGITOSESPDIARIO] [tinyint] NULL,
	[CONTIVA] [tinyint] NULL,
	[APLICARSECTOR] [tinyint] NULL,
	[SEGMENTOSECTOR] [tinyint] NULL,
	[DIGITOINICIALSECTOR] [tinyint] NULL,
	[NODIGITOSSECTOR] [tinyint] NULL,
	[APLICARUP] [tinyint] NULL,
	[SEGMENTOUP] [tinyint] NULL,
	[DIGITOINICIALUP] [tinyint] NULL,
	[NODIGITOSUP] [tinyint] NULL,
	[APLICARUR] [tinyint] NULL,
	[SEGMENTOUR] [tinyint] NULL,
	[DIGITOINICIALUR] [tinyint] NULL,
	[NODIGITOSUR] [tinyint] NULL,
	[APLICARESTADO] [tinyint] NULL,
	[SEGMENTOESTADO] [tinyint] NULL,
	[DIGITOINICIALESTADO] [tinyint] NULL,
	[NODIGITOSESTADO] [tinyint] NULL,
	[APLICARDIMENSION] [tinyint] NULL,
	[SEGMENTODIMENSION] [tinyint] NULL,
	[DIGITOINICIALDIMENSION] [tinyint] NULL,
	[NODIGITOSDIMENSION] [tinyint] NULL,
	[APLICARTEMATICAS] [tinyint] NULL,
	[SEGMENTOTEMATICAS] [tinyint] NULL,
	[DIGITOINICIALTEMATICAS] [tinyint] NULL,
	[NODIGITOSTEMATICAS] [tinyint] NULL,
	[APLICARPPAR] [tinyint] NULL,
	[SEGMENTOPPAR] [tinyint] NULL,
	[DIGITOINICIALPPAR] [tinyint] NULL,
	[NODIGITOSPPAR] [tinyint] NULL,
	[APLICARDESTGASTESP] [tinyint] NULL,
	[SEGMENTODESTGASTESP] [tinyint] NULL,
	[DIGITOINICIALDESTGASTESP] [tinyint] NULL,
	[NODIGITOSDESTGASTESP] [tinyint] NULL,
	[APLICARREGION] [tinyint] NULL,
	[SEGMENTOREGION] [tinyint] NULL,
	[DIGITOINICIALREGION] [tinyint] NULL,
	[NODIGITOSREGION] [tinyint] NULL,
	[APLICARMUNICIPIO] [tinyint] NULL,
	[SEGMENTOMUNICIPIO] [tinyint] NULL,
	[DIGITOINICIALMUNICIPIO] [tinyint] NULL,
	[NODIGITOSMUNICIPIO] [tinyint] NULL,
	[APLICARGENERO] [tinyint] NULL,
	[SEGMENTOGENERO] [tinyint] NULL,
	[DIGITOINICIALGENERO] [tinyint] NULL,
	[NODIGITOSGENERO] [tinyint] NULL,
	[APLICARCOMPONENTE] [tinyint] NULL,
	[SEGMENTOCOMPONENTE] [tinyint] NULL,
	[DIGITOINICIALCOMPONENTE] [tinyint] NULL,
	[NODIGITOSCOMPONENTE] [tinyint] NULL,
	[APLICARUEG] [tinyint] NULL,
	[SEGMENTOUEG] [tinyint] NULL,
	[DIGITOINICIALUEG] [tinyint] NULL,
	[NODIGITOSUEG] [tinyint] NULL,
	[APLICARSUBFFIN] [tinyint] NULL,
	[SEGMENTOSUBFFIN] [tinyint] NULL,
	[DIGITOINICIALSUBFFIN] [tinyint] NULL,
	[NODIGITOSSUBFFIN] [tinyint] NULL,
	[APLICARAR] [tinyint] NULL,
	[SEGMENTOAR] [tinyint] NULL,
	[DIGITOINICIALAR] [tinyint] NULL,
	[NODIGITOSAR] [tinyint] NULL,
	[AREACENTROCOSTO] [tinyint] NULL,
	[APLICARURINGRESOS] [tinyint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LUCCA410](
	[CODIGO] [int] NOT NULL,
	[1] [smallint] NULL,
	[2] [smallint] NULL,
	[3] [smallint] NULL,
	[4] [smallint] NULL,
	[5] [smallint] NULL,
	[6] [smallint] NULL,
	[7] [smallint] NULL,
	[8] [smallint] NULL,
	[9] [smallint] NULL,
	[10] [smallint] NULL,
	[11] [smallint] NULL,
	[12] [smallint] NULL,
	[13] [smallint] NULL,
	[14] [smallint] NULL,
	[15] [smallint] NULL,
	[16] [smallint] NULL,
	[17] [smallint] NULL,
	[18] [smallint] NULL,
	[19] [smallint] NULL,
	[20] [smallint] NULL,
	[21] [smallint] NULL,
	[22] [smallint] NULL,
	[23] [smallint] NULL,
	[24] [smallint] NULL,
	[25] [smallint] NULL,
	[26] [smallint] NULL,
	[27] [smallint] NULL,
	[28] [smallint] NULL,
	[29] [smallint] NULL,
	[30] [smallint] NULL,
	[31] [smallint] NULL,
	[32] [smallint] NULL,
	[33] [smallint] NULL,
	[34] [smallint] NULL,
	[35] [smallint] NULL,
	[36] [smallint] NULL,
	[37] [smallint] NULL,
	[38] [smallint] NULL,
	[39] [smallint] NULL,
	[40] [smallint] NULL,
	[41] [smallint] NULL,
	[42] [smallint] NULL,
	[43] [smallint] NULL,
	[44] [smallint] NULL,
	[45] [smallint] NULL,
	[46] [smallint] NULL,
	[47] [smallint] NULL,
	[48] [smallint] NULL,
	[49] [smallint] NULL,
	[50] [smallint] NULL,
	[51] [smallint] NULL,
	[52] [smallint] NULL,
	[53] [smallint] NULL,
	[54] [smallint] NULL,
	[55] [smallint] NULL,
	[56] [smallint] NULL,
	[57] [smallint] NULL,
	[58] [smallint] NULL,
	[59] [smallint] NULL,
	[60] [smallint] NULL,
	[61] [smallint] NULL,
	[62] [smallint] NULL,
	[63] [smallint] NULL,
	[64] [smallint] NULL,
	[65] [smallint] NULL,
	[66] [smallint] NULL,
	[67] [smallint] NULL,
	[68] [smallint] NULL,
	[69] [smallint] NULL,
	[70] [smallint] NULL,
	[71] [smallint] NULL,
	[72] [smallint] NULL,
	[73] [smallint] NULL,
	[74] [smallint] NULL,
	[75] [smallint] NULL,
	[76] [smallint] NULL,
	[77] [smallint] NULL,
	[78] [smallint] NULL,
	[79] [smallint] NULL,
	[80] [smallint] NULL,
	[81] [smallint] NULL,
	[82] [smallint] NULL,
	[83] [smallint] NULL,
	[84] [smallint] NULL,
	[85] [smallint] NULL,
	[86] [smallint] NULL,
	[87] [smallint] NULL,
	[88] [smallint] NULL,
	[89] [smallint] NULL,
	[90] [smallint] NULL,
	[91] [smallint] NULL,
	[92] [smallint] NULL,
	[93] [smallint] NULL,
	[94] [smallint] NULL,
	[95] [smallint] NULL,
	[96] [smallint] NULL,
	[97] [smallint] NULL,
	[98] [smallint] NULL,
	[99] [smallint] NULL,
	[100] [smallint] NULL,
	[101] [smallint] NULL,
	[102] [smallint] NULL,
	[103] [smallint] NULL,
	[104] [smallint] NULL,
	[105] [smallint] NULL,
	[106] [smallint] NULL,
	[107] [smallint] NULL,
	[108] [smallint] NULL,
	[109] [smallint] NULL,
	[110] [smallint] NULL,
	[111] [smallint] NULL,
	[112] [smallint] NULL,
	[113] [smallint] NULL,
	[114] [smallint] NULL,
	[115] [smallint] NULL,
	[116] [smallint] NULL,
	[117] [smallint] NULL,
	[118] [smallint] NULL,
	[119] [smallint] NULL,
	[120] [smallint] NULL,
	[121] [smallint] NULL,
	[122] [smallint] NULL,
	[123] [smallint] NULL,
	[124] [smallint] NULL,
	[125] [smallint] NULL,
	[126] [smallint] NULL,
	[127] [smallint] NULL,
	[128] [smallint] NULL,
	[129] [smallint] NULL,
	[130] [smallint] NULL,
	[131] [smallint] NULL,
	[132] [smallint] NULL,
	[133] [smallint] NULL,
	[134] [smallint] NULL,
	[135] [smallint] NULL,
	[136] [smallint] NULL,
	[137] [smallint] NULL,
	[138] [smallint] NULL,
	[139] [smallint] NULL,
	[140] [smallint] NULL,
	[141] [smallint] NULL,
	[142] [smallint] NULL,
	[143] [smallint] NULL,
	[144] [smallint] NULL,
	[145] [smallint] NULL,
	[146] [smallint] NULL,
	[147] [smallint] NULL,
	[148] [smallint] NULL,
	[149] [smallint] NULL,
	[150] [smallint] NULL,
	[151] [smallint] NULL,
	[152] [smallint] NULL,
	[153] [smallint] NULL,
	[154] [smallint] NULL,
	[155] [smallint] NULL,
	[156] [smallint] NULL,
	[157] [smallint] NULL,
	[158] [smallint] NULL,
	[159] [smallint] NULL,
	[160] [smallint] NULL,
	[161] [smallint] NULL,
	[162] [smallint] NULL,
	[163] [smallint] NULL,
	[164] [smallint] NULL,
	[165] [smallint] NULL,
	[166] [smallint] NULL,
	[167] [smallint] NULL,
	[168] [smallint] NULL,
	[169] [smallint] NULL,
	[170] [smallint] NULL,
	[171] [smallint] NULL,
	[172] [smallint] NULL,
	[173] [smallint] NULL,
	[174] [smallint] NULL,
	[175] [smallint] NULL,
	[176] [smallint] NULL,
	[177] [smallint] NULL,
	[178] [smallint] NULL,
	[179] [smallint] NULL,
	[180] [smallint] NULL,
	[181] [smallint] NULL,
	[182] [smallint] NULL,
	[183] [smallint] NULL,
	[184] [smallint] NULL,
	[185] [smallint] NULL,
	[186] [smallint] NULL,
	[187] [smallint] NULL,
	[188] [smallint] NULL,
	[189] [smallint] NULL,
	[190] [smallint] NULL,
	[191] [smallint] NULL,
	[192] [smallint] NULL,
	[193] [smallint] NULL,
	[194] [smallint] NULL,
	[195] [smallint] NULL,
	[196] [smallint] NULL,
	[197] [smallint] NULL,
	[198] [smallint] NULL,
	[199] [smallint] NULL,
	[200] [smallint] NULL,
	[201] [smallint] NULL,
	[202] [smallint] NULL,
	[203] [smallint] NULL,
	[204] [smallint] NULL,
	[205] [smallint] NULL,
	[206] [smallint] NULL,
	[207] [smallint] NULL,
	[208] [smallint] NULL,
	[209] [smallint] NULL,
	[210] [smallint] NULL,
	[211] [smallint] NULL,
	[212] [smallint] NULL,
	[213] [smallint] NULL,
	[214] [smallint] NULL,
	[215] [smallint] NULL,
	[216] [smallint] NULL,
	[217] [smallint] NULL,
	[218] [smallint] NULL,
	[219] [smallint] NULL,
	[220] [smallint] NULL,
	[221] [smallint] NULL,
	[222] [smallint] NULL,
	[223] [smallint] NULL,
	[224] [smallint] NULL,
	[225] [smallint] NULL,
	[226] [smallint] NULL,
	[227] [smallint] NULL,
	[228] [smallint] NULL,
	[229] [smallint] NULL,
	[230] [smallint] NULL,
	[231] [smallint] NULL,
	[232] [smallint] NULL,
	[233] [smallint] NULL,
	[234] [smallint] NULL,
	[235] [smallint] NULL,
	[236] [smallint] NULL,
	[237] [smallint] NULL,
	[238] [smallint] NULL,
	[239] [smallint] NULL,
	[240] [smallint] NULL,
	[241] [smallint] NULL,
	[242] [smallint] NULL,
	[243] [smallint] NULL,
	[244] [smallint] NULL,
	[245] [smallint] NULL,
	[246] [smallint] NULL,
	[247] [smallint] NULL,
	[248] [smallint] NULL,
	[249] [smallint] NULL,
	[250] [smallint] NULL,
	[251] [smallint] NULL,
	[252] [smallint] NULL,
	[253] [smallint] NULL,
	[254] [smallint] NULL,
	[255] [smallint] NULL,
	[256] [smallint] NULL,
	[257] [smallint] NULL,
	[258] [smallint] NULL,
	[259] [smallint] NULL,
	[260] [smallint] NULL,
	[261] [smallint] NULL,
	[262] [smallint] NULL,
	[263] [smallint] NULL,
	[264] [smallint] NULL,
	[265] [smallint] NULL,
	[266] [smallint] NULL,
	[267] [smallint] NULL,
	[268] [smallint] NULL,
	[269] [smallint] NULL,
	[270] [smallint] NULL,
	[271] [smallint] NULL,
	[272] [smallint] NULL,
	[273] [smallint] NULL,
	[274] [smallint] NULL,
	[275] [smallint] NULL,
	[276] [smallint] NULL,
	[277] [smallint] NULL,
	[278] [smallint] NULL,
	[279] [smallint] NULL,
	[280] [smallint] NULL,
	[281] [smallint] NULL,
	[282] [smallint] NULL,
	[283] [smallint] NULL,
	[284] [smallint] NULL,
	[285] [smallint] NULL,
	[286] [smallint] NULL,
	[287] [smallint] NULL,
	[288] [smallint] NULL,
	[289] [smallint] NULL,
	[290] [smallint] NULL,
	[291] [smallint] NULL,
	[292] [smallint] NULL,
	[293] [smallint] NULL,
	[294] [smallint] NULL,
	[295] [smallint] NULL,
	[296] [smallint] NULL,
	[297] [smallint] NULL,
	[298] [smallint] NULL,
	[299] [smallint] NULL,
	[300] [smallint] NULL,
	[301] [smallint] NULL,
	[302] [smallint] NULL,
	[303] [smallint] NULL,
	[304] [smallint] NULL,
	[305] [smallint] NULL,
	[306] [smallint] NULL,
	[307] [smallint] NULL,
	[308] [smallint] NULL,
	[309] [smallint] NULL,
	[310] [smallint] NULL,
	[311] [smallint] NULL,
	[312] [smallint] NULL,
	[313] [smallint] NULL,
	[314] [smallint] NULL,
	[315] [smallint] NULL,
	[316] [smallint] NULL,
	[317] [smallint] NULL,
	[318] [smallint] NULL,
	[319] [smallint] NULL,
	[320] [smallint] NULL,
	[321] [smallint] NULL,
	[322] [smallint] NULL,
	[323] [smallint] NULL,
	[324] [smallint] NULL,
	[325] [smallint] NULL,
	[326] [smallint] NULL,
	[327] [smallint] NULL,
	[328] [smallint] NULL,
	[329] [smallint] NULL,
	[330] [smallint] NULL,
	[331] [smallint] NULL,
	[332] [smallint] NULL,
	[333] [smallint] NULL,
	[334] [smallint] NULL,
	[335] [smallint] NULL,
	[336] [smallint] NULL,
	[337] [smallint] NULL,
	[338] [smallint] NULL,
	[339] [smallint] NULL,
	[340] [smallint] NULL,
	[341] [smallint] NULL,
	[342] [smallint] NULL,
	[343] [smallint] NULL,
	[344] [smallint] NULL,
	[345] [smallint] NULL,
	[346] [smallint] NULL,
	[347] [smallint] NULL,
	[348] [smallint] NULL,
	[349] [smallint] NULL,
	[350] [smallint] NULL,
	[351] [smallint] NULL,
	[352] [smallint] NULL,
	[353] [smallint] NULL,
	[354] [smallint] NULL,
	[355] [smallint] NULL,
	[356] [smallint] NULL,
	[357] [smallint] NULL,
	[358] [smallint] NULL,
	[359] [smallint] NULL,
	[360] [smallint] NULL,
	[361] [smallint] NULL,
	[362] [smallint] NULL,
	[363] [smallint] NULL,
	[364] [smallint] NULL,
	[365] [smallint] NULL,
	[366] [smallint] NULL,
	[367] [smallint] NULL,
	[368] [smallint] NULL,
	[369] [smallint] NULL,
	[370] [smallint] NULL,
	[371] [smallint] NULL,
	[372] [smallint] NULL,
	[373] [smallint] NULL,
	[374] [smallint] NULL,
	[375] [smallint] NULL,
 CONSTRAINT [PK_LUCCA410] PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LUCCA182](
	[CODIGO] [int] NOT NULL,
	[CTAEFEVOCAJA] [int] NULL,
	[FOLIOEXTERNOCAJERO] [int] NULL,
	[AUTCHEQUES] [tinyint] NULL,
	[AUTPAGOCOMPRAS] [tinyint] NULL,
	[AUTPAGOSERVICIOS] [tinyint] NULL,
	[AUTGASTOS] [tinyint] NULL,
	[AUTVARIACIONBIENES] [tinyint] NULL,
	[AUTVARIACIONSERVICIOS] [tinyint] NULL,
	[AUTOBRA] [tinyint] NULL,
	[AUTCONTRATOSGF] [tinyint] NULL,
	[AUTPAGOCONTRATOGF] [tinyint] NULL,
	[CAPTURAINCIDENCIASGRALES] [tinyint] NULL,
	[INCIDENCIASPARTICULARES] [tinyint] NULL,
	[CAPTURAPERCEPDEDUCGRALES] [tinyint] NULL,
	[CAPTURAPERCEPDEDUCPARTICULARES] [tinyint] NULL,
	[EDITAREMPRESA] [tinyint] NULL,
	[CATALOGOEMPLEADOS] [tinyint] NULL,
	[CALCULONOMINA] [tinyint] NULL,
	[DEDUCCIONES] [tinyint] NULL,
	[PARAMETROSGRALES] [tinyint] NULL,
	[PERCEPCIONES] [tinyint] NULL,
	[PLAZAS] [tinyint] NULL,
	[TABLAISR] [tinyint] NULL,
	[TABLASUBSIDIO] [tinyint] NULL,
	[CALCULARPTU] [tinyint] NULL,
	[OFICIOSCOMISION] [tinyint] NULL,
	[ZONAESPECIFICA] [tinyint] NULL,
	[FESTIVIDADES] [tinyint] NULL,
	[PERCEPCIONDEDUCCIONXLOTE] [tinyint] NULL,
	[CONFIGURACIONINTERFAZCONTABLE] [tinyint] NULL,
	[MATRICESCONVERSION] [tinyint] NULL,
	[CAJERO] [tinyint] NULL,
	[PADRON] [tinyint] NULL,
	[CATASTRO] [tinyint] NULL,
	[PREDIAL] [tinyint] NULL,
	[RESGUARDO] [tinyint] NULL,
	[DEPRESIACIONES] [tinyint] NULL,
	[MANIPULAUF] [int] NULL,
	[DERECHOCOMPRASTAREAS] [tinyint] NULL,
	[CUADRILLASALMACEN] [tinyint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LUCCA333](
	[CODIGO] [int] NOT NULL,
	[MENUPREF] [tinyint] NULL,
	[DER] [tinyint] NULL,
	[DERCUADFRIOB] [tinyint] NULL,
	[DERCUADFRIOS] [tinyint] NULL,
	[DERCOMPRASPROV] [tinyint] NULL,
	[DERFONREV] [tinyint] NULL,
	[DERCOMPGIROS] [tinyint] NULL,
	[DERLICITARREQ] [tinyint] NULL,
	[DERADJUDICARREQB] [tinyint] NULL,
	[DERADJUDICARREQS] [tinyint] NULL,
	[DERLICITAINICIO] [tinyint] NULL,
	[DERLICITAINVITA] [tinyint] NULL,
	[DERLICITATECNICA] [tinyint] NULL,
	[DERLICITAECONOMICA] [tinyint] NULL,
	[DERLICITAADJUDICA] [tinyint] NULL,
	[DERCONTRATOSMODELO] [tinyint] NULL,
	[DERCONTRATOSBIENES] [tinyint] NULL,
	[DERCONTRATOSSERVICIOS] [tinyint] NULL,
	[DERCONTRATOSOBRA] [tinyint] NULL,
	[DERCONTRATOSGASTOSFIJOS] [tinyint] NULL,
	[DERCONTRATOSMODELOLICITA] [tinyint] NULL,
	[DERTRANSPARENCIA] [tinyint] NULL,
	[DERPROGRAMASSOCIALES] [tinyint] NULL,
	[DERNORMATECAMODIFICA] [tinyint] NULL,
	[DERAUTORIZARVIATICO] [tinyint] NULL,
	[DERAUTPROCVIATICO] [tinyint] NULL,
	[NivelAutGlosa] [smallint] NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[LUCCA466](
	[Mac] [varchar](20) NULL,
	[UltUsuario] [int] NULL,
	[PenUsuario] [int] NULL,
	[AntUsuario] [int] NULL,
	[Bloqueado] [tinyint] NULL,
	[MotivoBloqueo] [varchar](50) NULL,
	[UltPostit] [int] NULL
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[UsuHist](
	[CODIGO] [int] NOT NULL,
	[CONTRASENA] [varchar](19) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODIGO] ASC,
	[CONTRASENA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[BitMovs](
	[FECHAHORA] [datetime] NOT NULL,
	[USUARIO] [int] NOT NULL,
	[NIVEL] [smallint] NULL,
	[PROCESO] [varchar](20) NULL,
	[MODALIDAD] [varchar](50) NULL,
	[REGISTRO] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[FECHAHORA] ASC,
	[USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE VIEW [dbo].[vw_Usuarios] AS SELECT u.*, 
CASE WHEN u.ULTIMOREGISTRO IS NULL THEN NULL ELSE CONVERT(date, DATEADD(day, CAST(u.ULTIMOREGISTRO AS int) - 362, CONVERT(date,'1800-12-28')))
END AS ULTIMOREGISTRO_DT FROM dbo.Usuarios u;
GO

CREATE VIEW [dbo].[vw_Solicitudes] AS SELECT s.*, 
CASE WHEN s.FECHA IS NULL 
THEN NULL ELSE CONVERT(date, DATEADD(day, CAST(s.FECHA AS int) - 362, CONVERT(date,'1800-12-28'))) END AS FECHA_DT_EFFECTIVE FROM dbo.Solicitudes s; 
GO

CREATE VIEW [dbo].[vw_AtencionServicios] AS SELECT a.*, 
CASE WHEN a.FECHA IS NULL THEN NULL ELSE CONVERT(date, DATEADD(day, CAST(a.FECHA AS int) - 362, 
CONVERT(date,'1800-12-28'))) END AS FECHA_DT_EFFECTIVE FROM dbo.AtencionServicios a; 
GO
